name: "snyk code test"
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: snyk/actions/setup@master
      - name: Snyk Test
        run: snyk code test --org=${{ secrets.SNYK_ORG }} --severity-threshold=high
        continue-on-error: false
        env:
           SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      - name: Snyk OS Test
        run: snyk test --org=${{ secrets.SNYK_ORG }} --severity-threshold=high
        continue-on-error: false
        env:
           SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

